### ISSUE TITLE
[Bug Report]: Server crash on startup

### ISSUE THREAD

**Issue by jmarler** [TeamAOF/Craftoria#205]
### Modpack Version

1.50

### Describe your issue.

Server crashes upon startup. I'm running the server in docker so it should be fairly easy to reproduce. I'm using itzg/minecraft-server:java21-graalvm and have tried many variations of java21, some working better than others, but it either immediately fails completely, or attempts to start, then crashes with this:

`
[17Oct2024 03:01:36.773] [modloading-worker-0/WARN] [net.neoforged.neoforge.common.ModConfigSpec/CORE]: Incorrect key materials.refined_obsidian.refined_obsidianHoeDamage was corrected from -8.0 to its default, -8.0. 
[17Oct2024 03:01:36.874] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 2 errors found
[17Oct2024 03:01:37.205] [main/ERROR] [net.minecraft.CrashReport/]: Negative index in crash report handler (0/18)
[17Oct2024 03:01:37.245] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 7a1bbd06-3a9e-4087-9093-11f444d84523
[17Oct2024 03:01:37.251] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-10-17_03.01.37-fml.txt
[17Oct2024 03:01:37.263] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 4a7e0cd1-db69-404d-8a2d-24c15fb33f01
[17Oct2024 03:01:37.266] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
	- Lighty (lighty) has failed to load correctly
	  java.lang.NoClassDefFoundError: net/minecraft/client/OptionInstance$ValueSet
	- Chat Toggle (chattoggle) has failed to load correctly
	  java.lang.ExceptionInInitializerError: null
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.24.jar%2360!/:4.0]
	at TRANSFORMER/neoforge@21.1.66/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.1.66-universal.jar%23405!/:?]
	at TRANSFORMER/neoforge@21.1.66/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.1.66-universal.jar%23405!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21.1-20240808.144430-srg.jar%23404!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%2360!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
`

Command used to start docker:
`docker run -d -it -p 25565:25565 --env-file=craftoria-env -v ./craftoria:/data -v ./craftoria/manifests:/manifests:ro --name craftoria itzg/minecraft-server:java21-graalvm
`

Environment file:
`CF_MODPACK_ZIP=/data/Craftoria-1.5.0.zip
CF_API_KEY=xxxx
EULA=TRUE
MEMORY=8G
TYPE=NEOFORGE
NEOFORGE_VERSION=21.1.66
VERSION=1.21.1
CF_SLUG=craftoria
CF_MODPACK_MANIFEST=/manifests/manifest.json
MOD_PLATFORM=AUTO_CURSEFORGE
CF_PARALLEL_DOWNLOADS=4
UID=501
`

I am using the manifest from https://mediafilez.forgecdn.net/files/5803/608/Craftoria-1.5.0.zip downloaded and extracted. I have also tried using the AUTO_CURSEFORGE type letting it handle downloading the manifest, but was concerned that it was using the client version of the server, so I switched gears and used the manifest from the modpack zip specified in the server installer yaml file. The results are the same regardless. The server always crashes via the lighty module. 

### Crash Report

https://gist.github.com/jmarler/16e1d0bc1cb73b636b359129f5ef28b9

### Latest Log

https://gist.github.com/jmarler/16e1d0bc1cb73b636b359129f5ef28b9

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by SubordinalBlue** [comment]
The use of docker is the problem, in this case.
The server files are intended to be installed by running the included start script.

Maybe try again with out it, as a little science 'ground case'.

**Comment by jmarler** [comment]
I added the projects listed in the server installer, and I can get the server to start ... but it constantly barfs errors about the configuration files being invalid and being corrected for MekanismTools and TorchMaster:

`[17Oct2024 06:35:04.316] [pool-13-thread-1/WARN] [net.neoforged.fml.config.ConfigTracker/CONFIG]: Configuration file /data/config/torchmaster.toml is not correct. Correcting
[17Oct2024 06:35:04.326] [pool-13-thread-1/WARN] [net.neoforged.neoforge.common.ModConfigSpec/CORE]: Configuration LoadedConfig[config=SynchronizedConfig{DataHolder:{General=SynchronizedConfig{DataHolder:{beginnerTooltips=true, blockOnlyNaturalSpawns=true, lycanitesMobsBlockAll=true, blockVillageSieges=true, megaTorchRadius=64, dreadLampRadius=64, megaTorchEntityBlockListOverrides=[], dreadLampEntityBlockListOverrides=[], feralFlareRadius=16, feralFlareTickRate=5, feralFlareMinLightLevel=10, feralFlareLanternLightCountHardcap=255, frozenPearlDurability=1024, logSpawnChecks=false, aggressiveSpawnChecks=false}}}}, path=/data/config/torchmaster.toml, modConfig=net.neoforged.fml.config.ModConfig@7baa11e0] is not correct. Correcting
[17Oct2024 06:35:04.818] [pool-13-thread-1/WARN] [net.neoforged.fml.config.ConfigTracker/CONFIG]: Configuration file /data/config/Mekanism/tools-materials-startup.toml is not correct. Correcting
[17Oct2024 06:35:04.829] [pool-13-thread-1/WARN] [net.neoforged.neoforge.common.ModConfigSpec/CORE]: Configuration LoadedConfig[config=SynchronizedConfig{DataHolder:{materials=SynchronizedConfig{DataHolder:{wood=SynchronizedConfig{DataHolder:{woodPaxelDamage=7.0, woodPaxelAtkSpeed=-2.4000000953674316, woodPaxelEfficiency=2.0, woodPaxelEnchantability=15, woodPaxelDurability=118}}, stone=SynchronizedConfig{DataHolder:{stonePaxelDamage=8.0, stonePaxelAtkSpeed=-2.4000000953674316, stonePaxelEfficiency=4.0, stonePaxelEnchantability=5, stonePaxelDurability=262}}, gold=SynchronizedConfig{DataHolder:{goldPaxelDamage=7.0, goldPaxelAtkSpeed=-2.4000000953674316, goldPaxelEfficiency=12.0, goldPaxelEnchantability=22, goldPaxelDurability=64}}, iron=SynchronizedConfig{DataHolder:{ironPaxelDamage=7.0, ironPaxelAtkSpeed=-2.4000000953674316, ironPaxelEfficiency=6.0, ironPaxelEnchantability=14, ironPaxelDurability=500}}, diamond=SynchronizedConfig{DataHolder:{diamondPaxelDamage=6.0, diamondPaxelAtkSpeed=-2.4000000953674316, diamondPaxelEfficiency=8.0, diamondPaxelEnchantability=10, diamondPaxelDurability=3122}}, netherite=SynchronizedConfig{DataHolder:{netheritePaxelDamage=6.0, netheritePaxelAtkSpeed=-2.4000000953674316, netheritePaxelEfficiency=9.0, netheritePaxelEnchantability=15, netheritePaxelDurability=4062}}, lapis_lazuli=SynchronizedConfig{DataHolder:{lapis_lazuliToolDurability=128, lapis_lazuliEfficiency=9.0, lapis_lazuliAttackDamage=1.0, lapis_lazuliEnchantability=32, lapis_lazuliShieldDurability=224, lapis_lazuliSwordDamage=3.0, lapis_lazuliSwordAtkSpeed=-2.4000000953674316, lapis_lazuliShovelDamage=1.5, lapis_lazuliShovelAtkSpeed=-3.0, lapis_lazuliAxeDamage=4.0, lapis_lazuliAxeAtkSpeed=-2.9000000953674316, lapis_lazuliPickaxeDamage=1.0, lapis_lazuliPickaxeAtkSpeed=-2.799999952316284, lapis_lazuliHoeDamage=-1.0, lapis_lazuliHoeAtkSpeed=-2.0, lapis_lazuliPaxelDamage=5.0, lapis_lazuliPaxelAtkSpeed=-2.4000000953674316, lapis_lazuliPaxelEfficiency=9.0, lapis_lazuliPaxelEnchantability=32, lapis_lazuliPaxelDurability=256, lapis_lazuliToughness=0.0, lapis_lazuliKnockbackResistance=0.0, lapis_lazuliBootDurability=130, lapis_lazuliBootArmor=1, lapis_lazuliLeggingDurability=150, lapis_lazuliLeggingArmor=3, lapis_lazuliChestplateDurability=160, lapis_lazuliChestplateArmor=4, lapis_lazuliHelmetDurability=110, lapis_lazuliHelmetArmor=1}}, bronze=SynchronizedConfig{DataHolder:{bronzeToolDurability=375, bronzeEfficiency=7.0, bronzeAttackDamage=2.0, bronzeEnchantability=10, bronzeShieldDurability=403, bronzeSwordDamage=3.0, bronzeSwordAtkSpeed=-2.4000000953674316, bronzeShovelDamage=1.5, bronzeShovelAtkSpeed=-3.0, bronzeAxeDamage=7.0, bronzeAxeAtkSpeed=-3.0, bronzePickaxeDamage=1.0, bronzePickaxeAtkSpeed=-2.799999952316284, bronzeHoeDamage=-2.0, bronzeHoeAtkSpeed=-1.0, bronzePaxelDamage=8.0, bronzePaxelAtkSpeed=-2.4000000953674316, bronzePaxelEfficiency=7.0, bronzePaxelEnchantability=10, bronzePaxelDurability=750, bronzeToughness=1.0, bronzeKnockbackResistance=0.0, bronzeBootDurability=234, bronzeBootArmor=2, bronzeLeggingDurability=270, bronzeLeggingArmor=6, bronzeChestplateDurability=288, bronzeChestplateArmor=7, bronzeHelmetDurability=198, bronzeHelmetArmor=3}}, osmium=SynchronizedConfig{DataHolder:{osmiumToolDurability=350, osmiumEfficiency=4.0, osmiumAttackDamage=4.0, osmiumEnchantability=14, osmiumShieldDurability=672, osmiumSwordDamage=3.0, osmiumSwordAtkSpeed=-2.4000000953674316, osmiumShovelDamage=1.5, osmiumShovelAtkSpeed=-3.0, osmiumAxeDamage=8.0, osmiumAxeAtkSpeed=-3.299999952316284, osmiumPickaxeDamage=1.0, osmiumPickaxeAtkSpeed=-2.799999952316284, osmiumHoeDamage=-4.0, osmiumHoeAtkSpeed=1.0, osmiumPaxelDamage=9.0, osmiumPaxelAtkSpeed=-2.4000000953674316, osmiumPaxelEfficiency=4.0, osmiumPaxelEnchantability=14, osmiumPaxelDurability=700, osmiumToughness=3.0, osmiumKnockbackResistance=0.10000000149011612, osmiumBootDurability=250, osmiumBootArmor=3, osmiumLeggingDurability=300, osmiumLeggingArmor=6, osmiumChestplateDurability=300, osmiumChestplateArmor=7, osmiumHelmetDurability=250, osmiumHelmetArmor=3}}, steel=SynchronizedConfig{DataHolder:{steelToolDurability=500, steelEfficiency=7.0, steelAttackDamage=3.0, steelEnchantability=16, steelShieldDurability=448, steelSwordDamage=3.0, steelSwordAtkSpeed=-2.4000000953674316, steelShovelDamage=1.5, steelShovelAtkSpeed=-3.0, steelAxeDamage=7.0, steelAxeAtkSpeed=-3.0, steelPickaxeDamage=1.0, steelPickaxeAtkSpeed=-2.799999952316284, steelHoeDamage=-3.0, steelHoeAtkSpeed=0.0, steelPaxelDamage=8.0, steelPaxelAtkSpeed=-2.4000000953674316, steelPaxelEfficiency=8.0, steelPaxelEnchantability=16, steelPaxelDurability=1000, steelToughness=2.0, steelKnockbackResistance=0.0, steelBootDurability=300, steelBootArmor=3, steelLeggingDurability=350, steelLeggingArmor=6, steelChestplateDurability=350, steelChestplateArmor=8, steelHelmetDurability=300, steelHelmetArmor=3}}, refined_glowstone=SynchronizedConfig{DataHolder:{refined_glowstoneToolDurability=384, refined_glowstoneEfficiency=13.0, refined_glowstoneAttackDamage=2.0, refined_glowstoneEnchantability=20, refined_glowstoneShieldDurability=381, refined_glowstoneSwordDamage=3.0, refined_glowstoneSwordAtkSpeed=-2.4000000953674316, refined_glowstoneShovelDamage=1.5, refined_glowstoneShovelAtkSpeed=-3.0, refined_glowstoneAxeDamage=6.0, refined_glowstoneAxeAtkSpeed=-2.9000000953674316, refined_glowstonePickaxeDamage=1.0, refined_glowstonePickaxeAtkSpeed=-2.799999952316284, refined_glowstoneHoeDamage=-2.0, refined_glowstoneHoeAtkSpeed=-1.0, refined_glowstonePaxelDamage=7.0, refined_glowstonePaxelAtkSpeed=-2.4000000953674316, refined_glowstonePaxelEfficiency=13.0, refined_glowstonePaxelEnchantability=20, refined_glowstonePaxelDurability=768, refined_glowstoneToughness=0.0, refined_glowstoneKnockbackResistance=0.0, refined_glowstoneBootDurability=221, refined_glowstoneBootArmor=3, refined_glowstoneLeggingDurability=255, refined_glowstoneLeggingArmor=6, refined_glowstoneChestplateDurability=272, refined_glowstoneChestplateArmor=7, refined_glowstoneHelmetDurability=187, refined_glowstoneHelmetArmor=3}}, refined_obsidian=SynchronizedConfig{DataHolder:{refined_obsidianAttackDamage=5.0, refined_obsidianShieldDurability=1680, refined_obsidianSwordDamage=3.0, refined_obsidianSwordAtkSpeed=-2.4000000953674316, refined_obsidianShovelDamage=1.5, refined_obsidianShovelAtkSpeed=-3.0, refined_obsidianAxeDamage=7.0, refined_obsidianAxeAtkSpeed=-2.9000000953674316, refined_obsidianPickaxeDamage=1.0, refined_obsidianPickaxeAtkSpeed=-2.799999952316284, refined_obsidianHoeDamage=-8.0, refined_obsidianHoeAtkSpeed=5.0, refined_obsidianEfficiency=10.0, refined_obsidianPaxelDamage=8.0, refined_obsidianPaxelAtkSpeed=-2.4000000953674316, refined_obsidianPaxelEfficiency=10.0, refined_obsidianPaxelEnchantability=18, refined_obsidianEnchantability=18, refined_obsidianToughness=3.0, refined_obsidianKnockbackResistance=0.20000000298023224, refined_obsidianBootDurability=429, refined_obsidianLeggingDurability=495, refined_obsidianChestplateDurability=528, refined_obsidianHelmetDurability=363, refined_obsidianBootArmor=5, refined_obsidianLeggingArmor=7, refined_obsidianChestplateArmor=9, refined_obsidianHelmetArmor=5, refined_obsidianToolDurability=1000, refined_obsidianPaxelDurability=2000}}}}}}, path=/data/config/Mekanism/tools-materials-startup.toml, modConfig=net.neoforged.fml.config.ModConfig@3044940a] is not correct. Correcting
`

**Comment by jmarler** [comment]
Megatorch v21.1.3 fixes the log spam for that mod. I don't see a similar fix for MekanismTools, but it's likely an upstream issue. I'll close this report here and report in Mekanism about the log spam.
